/**
 * Pogoda.cc
 * Backend API specification for pogoda.cc system
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: sp8ebc@interia.pl
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * MeteoSystemApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_MeteoSystemApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_MeteoSystemApi_H_


#include "../ApiClient.h"

#include "StationGroupStations.h"
#include "StationsGroup.h"


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  MeteoSystemApi 
{
public:

    explicit MeteoSystemApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~MeteoSystemApi();

    /// <summary>
    /// Returns a list of all station groups defined in the system
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<std::vector<std::shared_ptr<StationsGroup>>> groupsAllGet(
    ) const;
    /// <summary>
    /// Returns all stations associated with given group
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id"></param>
    pplx::task<std::vector<std::shared_ptr<StationGroupStations>>> groupsStationsIdGet(
        int32_t id
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_MeteoSystemApi_H_ */

