/**
 * Pogoda.cc
 * Backend API specification for pogoda.cc system
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: sp8ebc@interia.pl
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * QualityFactor.h
 *
 * Quality Factor
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_QualityFactor_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_QualityFactor_H_


#include "../ModelBase.h"


namespace org {
namespace openapitools {
namespace client {
namespace model {

class  QualityFactor
    : public ModelBase
{
public:
    QualityFactor();
    virtual ~QualityFactor();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    enum class eQualityFactor
    {
        QualityFactor_FULL_,
        QualityFactor_DEGRADED_,
        QualityFactor_NOT_AVALIABLE_,
        QualityFactor_NO_DATA,
    };

    eQualityFactor getValue() const;
    void setValue(eQualityFactor const value);

    protected:
        eQualityFactor m_value;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_QualityFactor_H_ */
