/**
 * Pogoda.cc
 * Backend API specification for pogoda.cc system
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: sp8ebc@interia.pl
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * StationGroupStations.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_StationGroupStations_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_StationGroupStations_H_


#include "../ModelBase.h"

#include <vector>
#include "StationGroupStationsStation.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  StationGroupStations
    : public ModelBase
{
public:
    StationGroupStations();
    virtual ~StationGroupStations();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// StationGroupStations members

    /// <summary>
    /// 
    /// </summary>
    int32_t getStationGroupId() const;
    bool stationGroupIdIsSet() const;
    void unsetStationGroupId();

    void setStationGroupId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<StationGroupStationsStation>>& getStationIds();
    bool stationIdsIsSet() const;
    void unsetStationIds();

    void setStationIds(const std::vector<std::shared_ptr<StationGroupStationsStation>>& value);


protected:
    int32_t m_StationGroupId;
    bool m_StationGroupIdIsSet;
    std::vector<std::shared_ptr<StationGroupStationsStation>> m_StationIds;
    bool m_StationIdsIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_StationGroupStations_H_ */
