/**
 * Pogoda.cc
 * Backend API specification for pogoda.cc system
 *
 * The version of the OpenAPI document: 1.0.11
 * Contact: sp8ebc@interia.pl
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * StationGroupStationsStation.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_StationGroupStationsStation_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_StationGroupStationsStation_H_


#include "../ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  StationGroupStationsStation
    : public ModelBase
{
public:
    StationGroupStationsStation();
    virtual ~StationGroupStationsStation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// StationGroupStationsStation members

    /// <summary>
    /// 
    /// </summary>
    int32_t getStationId() const;
    bool stationIdIsSet() const;
    void unsetStationId();

    void setStationId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getStationName() const;
    bool stationNameIsSet() const;
    void unsetStationName();

    void setStationName(const utility::string_t& value);


protected:
    int32_t m_StationId;
    bool m_StationIdIsSet;
    utility::string_t m_StationName;
    bool m_StationNameIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_StationGroupStationsStation_H_ */
