/**
 * Meteoblue Package API - day & 3h
 * This yaml contains a description of basic_day and basic_3h from Package API provided by Meteoblue
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Inline_response_200.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Inline_response_200_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Inline_response_200_H_


#include "../ModelBase.h"

#include "Data_day.h"
#include "Units.h"
#include "Metadata.h"
#include "Data_3h.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {


/// <summary>
/// 
/// </summary>
class  Inline_response_200
    : public ModelBase
{
public:
    Inline_response_200();
    virtual ~Inline_response_200();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Inline_response_200 members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Metadata> getMetadata() const;
    bool metadataIsSet() const;
    void unsetMetadata();

    void setMetadata(const std::shared_ptr<Metadata>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Units> getUnits() const;
    bool unitsIsSet() const;
    void unsetUnits();

    void setUnits(const std::shared_ptr<Units>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Data_3h> getData3h() const;
    bool data3hIsSet() const;
    void unsetData_3h();

    void setData3h(const std::shared_ptr<Data_3h>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Data_day> getDataDay() const;
    bool dataDayIsSet() const;
    void unsetData_day();

    void setDataDay(const std::shared_ptr<Data_day>& value);


protected:
    std::shared_ptr<Metadata> m_Metadata;
    bool m_MetadataIsSet;
    std::shared_ptr<Units> m_Units;
    bool m_UnitsIsSet;
    std::shared_ptr<Data_3h> m_Data_3h;
    bool m_Data_3hIsSet;
    std::shared_ptr<Data_day> m_Data_day;
    bool m_Data_dayIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Inline_response_200_H_ */
