/**
 * Meteoblue Package API - day & 3h
 * This yaml contains a description of basic_day and basic_3h from Package API provided by Meteoblue
 *
 * The version of the OpenAPI document: 1.0.11
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.3.1.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * ForecastApi.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_API_ForecastApi_H_
#define ORG_OPENAPITOOLS_CLIENT_API_ForecastApi_H_


#include "../ApiClient.h"

#include "Inline_response_200.h"
#include <cpprest/details/basic_types.h>


#include <boost/optional.hpp>

namespace org {
namespace openapitools {
namespace client {
namespace api {

using namespace org::openapitools::client::model;



class  ForecastApi 
{
public:

    explicit ForecastApi( std::shared_ptr<const ApiClient> apiClient );

    virtual ~ForecastApi();

    /// <summary>
    /// 
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="lon"></param>
    /// <param name="lat"></param>
    /// <param name="timeformat"></param>
    /// <param name="apikey"></param>
    /// <param name="sig"> (optional, default to utility::conversions::to_string_t(&quot;&quot;))</param>
    pplx::task<std::shared_ptr<Inline_response_200>> basicDayBasic3hGet(
        float lon,
        float lat,
        utility::string_t timeformat,
        utility::string_t apikey,
        boost::optional<utility::string_t> sig
    ) const;

protected:
    std::shared_ptr<const ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_API_ForecastApi_H_ */

